// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Answer struct {
	Answer string `json:"answer"`
}

type Comment struct {
	ID       string  `json:"id"`
	UserID   string  `json:"userId"`
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Content  string  `json:"content"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	UserID          string     `json:"userId"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
